### ISSUE TITLE
Detailed instructions for someone to quick-start and run this, without the need of anything Matrix related

### ISSUE THREAD

**Issue by ashfame** [Automattic/matrix-workflow-builder#8]
- [x] Add a dummy workflowstep that simply outputs to stdout for demo purposes.
- [x] Skip all the matrix related flags parsing
- [x] Separate out matrix initialization from engine startup, so that engine can run without having to do with matrix
- [x] Will still need instructions to add database entries. Perhaps a better starting point is to have a bash script one can run to give them a sqlite db to work with. Much easier to look into and make changes accordingly as per instructions.

**Comment by ashfame** [comment]
Made use of migration script to add records when database schema is created upon first run.

**Comment by ashfame** [comment]
@akirk Can you checkout the [readme](https://github.com/Automattic/matrix-workflow-builder#readme) once and see if this clearly conveys the functionality in action?

**Comment by akirk** [comment]
This is better, thanks! I think it would be useful to add a section on "Adding your own workflow." It's not obvious that this is database driven and how the workflow steps are invoked.

**Comment by ashfame** [comment]
@akirk Good point! I added some instructions for the same.
